name: Versioning

on:
  push:
    branches: 
      - "main"

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs: 
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: v1-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn

      - name: Build
        run: yarn version